clone_folder: c:\project\opencpn
shallow_clone: true

platform: x64
configuration: Release
deploy: OFF
test: OFF

install:
  - set WXWIN=C:\wxWidgets-3.0.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll

  - ls "c:\program files (x86)\Microsoft SDKs"
  - ls "c:\program files (x86)\Microsoft SDKs\Windows"
  - ls "c:\program files (x86)\Microsoft SDKs\Windows\v8.1A"
  - ls "c:\program files (x86)\Microsoft SDKs\Windows\v8.1A\Bin"
  - '"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\Bin\SetEnv.cmd" /x64'
  - cmd: cinst poedit -x86

  # download & extract wxWidgets
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.zip
  - cmd: 7z x wxwidgets-3.0.2.zip -o%WXWIN% > null
  - cmd: SET PATH=%PATH%;%WXWIN%;%WXWIN%\lib\vc_dll;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # some debugging information
  - set
  - cmake --help

  # build wxWidgets
  - cmd: cd %WXWIN%\build\msw\
  - cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\project\opencpn
  - mkdir build
  - cd build
  - cmake -T v120_xp ..

build_script:
  - cmake --build . --config Release --target package
