clone_folder: c:\project\opencpn
shallow_clone: true

platform: x64
configuration: Release
deploy: OFF
test: OFF

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - cmd: SET WINDOWS_SDK_VERSION="v7.1"

  - choco install wxwidgets poedit -x86
  - set WXWIN=C:\wxWidgets-3.0.2

  - cmd: SET PATH=%PATH%;%WXWIN%;%WXWIN%\lib\vc_dll;C:\Program Files (x86)\Poedit\Gettexttools\bin;
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll

  # some debugging information
  - set
  # - cmake --help

before_build:
  - cd c:\project\opencpn
  - mkdir build
  - cd build
  - cmake -T v120_xp ..
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/OpenCPN_buildwin.7z
  - cmd: 7z x OpenCPN_buildwin.7z -o c:\project\opencpn

build_script:
  - cmake --build . --config Release --target package
