clone_folder: c:\project\opencpn
shallow_clone: true

platform: x64
configuration: Release
deploy: OFF
test: OFF

install:
  - set WXWIN=C:\wxWidgets-2.8.12
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/2.8.12/wxWidgets-2.8.12.zip
  - cmd: 7z x wxwidgets-2.8.12.zip -oc:\
  - cmd: SET PATH=%PATH%;C:\wxWidgets-2.8.12;%WXWIN%\lib\vc_lib;C:\Program Files\Poedit\bin;
  - cmd: cd C:\wxWidgets-2.8.12\build\msw\
  - ls C:\wxWidgets-2.8.12
  - cmd: nmake -f makefile.vc BUILD=release SHARED=1
  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1
  - cmd: cinst poedit -x86

before_build:
  - call "C:\Program Files\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - set
  - cmake
  - cmd: cd c:\project\opencpn
  - cmd: ls %wxWidgets_LIB_DIR%
  - mkdir build
  - ps: cd build
  - cmake ..
  #- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\wxWidgets -DCMAKE_PROGRAM_PATH=C:\cygwin\bin ..

build_script:
  - cmake --build . --config Release --target package

# inspiration from:
# - https://github.com/alex85k/osm2pgsql-cmake/blob/984582bfae2f1344e75db48c04daf70bcaca518c/appveyor.yml
# - https://github.com/antonvw/wxExtension/blob/master/appveyor.yml
  # - ps: Start-FileDownload 'http://sourceforge.net/projects/syncped/files/wxWidgets-3.1.0-include.7z'
  # - ps: Start-FileDownload 'http://sourceforge.net/projects/syncped/files/wxWidgets-3.1.0-lib.7z'
  # - ps: Start-FileDownload 'http://sourceforge.net/projects/syncped/files/wxWidgets-3.1.0-locale.7z'
  # - cmd: 7z x wxWidgets-3.1.0-include.7z -oC:\wxWidgets
  # - cmd: 7z x wxWidgets-3.1.0-lib.7z -oC:\wxWidgets
  # - cmd: 7z x wxWidgets-3.1.0-locale.7z -oC:\wxWidgets
  # - ps: Start-FileDownload 'http://downloads.sourceforge.net/project/wxwindows/3.0.2/binaries/wxMSW-3.0.2_vc120_Dev.7z'
  # - ps: Start-FileDownload 'http://downloads.sourceforge.net/project/wxwindows/3.0.2/binaries/wxMSW-3.0.2_vc120_x64_Dev.7z
  # - cmd: 7z x wxMSW-3.0.2_vc120_Dev.7z -oC:\wxWidgets
