clone_folder: c:\project\opencpn
shallow_clone: true

platform: x64
configuration: Release
deploy: OFF
test: OFF

install:
  - set WXWIN=C:\wxWidgets-3.0.2
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.zip
# - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/2.8.12/wxWidgets-2.8.12.zip
  - cmd: 7z x wxwidgets-3.0.2.zip -oc:\
  - cmd: SET PATH=%PATH%;%WXWIN%;%WXWIN%\lib\vc_dll;C:\Program Files\Poedit\bin;
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: cd %WXWIN%\build\msw\
  - cmd: nmake -f makefile.vc BUILD=release SHARED=1
  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1
  - cmd: cinst poedit -x86
  - cmake --help
  - set

before_build:
  - cmd: cd c:\project\opencpn
  - cmd: ls %wxWidgets_LIB_DIR%
  - mkdir build
  - ps: cd build
  - cmake -G "Visual Studio 12 2013" -DwxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll ..

build_script:
  - cmake --build . --config Release --target package

# inspiration from:
# - https://github.com/alex85k/osm2pgsql-cmake/blob/984582bfae2f1344e75db48c04daf70bcaca518c/appveyor.yml
# - https://github.com/antonvw/wxExtension/blob/master/appveyor.yml
